ARG TAG_ANTS

FROM pennlinc/qsiprep-ants:${TAG_ANTS} as base
FROM base as builder
RUN wget -O /tmp/cuda-keyring.deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i /tmp/cuda-keyring.deb && \
    rm /tmp/cuda-keyring.deb

RUN apt update && apt full-upgrade -y && \
  apt install --no-install-recommends -y \
    software-properties-common \
    zlib1g-dev \
    wget \
    git \
    build-essential \
    libeigen3-dev \
    fftw3 \
    libfftw3-dev \
    gnupg \
    ca-certificates \
    apt-transport-https && \
  wget -O /tmp/kitware-archive.key https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null && \
  gpg --dearmor /tmp/kitware-archive.key && \
  mv /tmp/kitware-archive.key.gpg /usr/share/keyrings/kitware-archive-keyring.gpg && \
  echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main" > /etc/apt/sources.list.d/kitware.list && \
  apt-get update && \
  apt-get -y install cmake cmake-data && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN \
  mkdir /src \
  && cd /src \
  && wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz \
  && tar -xvf boost_1_77_0.tar.gz \
  && cd boost_1_77_0 \
  && ./bootstrap.sh --with-libraries=iostreams,filesystem,system,regex --prefix=/usr/local/boost176 \
  && ./b2 install


ARG TORTOISE_SHA=5d0c688e85fd12a974d2ecbd8b567913a0b46c4f
RUN \
  cd /src \
  && git clone https://github.com/eurotomania/TORTOISEV4.git \
  && cd TORTOISEV4/TORTOISEV4 \
  && git checkout ${TORTOISE_SHA} \
  && sed -i '/BrukerBmatToTORTOISEBMTXT/d' CMakeLists.txt \
  && cmake . \
      -DUSECUDA=1 \
      -DQSIPREP=1 \
      -DITK_DIR=/tmp/ants/build/ITKv5-build \
      -DISDEBUG=0 \
      && \
    make

CMD ["/bin/bash"]
