# Portions of this code are from the original DSI Studio build files
FROM ubuntu:jammy-20240125
ARG TAG_ANTS

ENV DEBIAN_FRONTEND noninteractive

# Prepare environment
RUN apt update && apt upgrade -y && \
  apt install -y \
  unzip \
  curl \
  git \
  zlib1g-dev \
  libglu1-mesa-dev \
  qt6-base-dev \
  libqt6charts6-dev \
  libqt6opengl6-dev \
  qt6-image-formats-plugins \
  gcc-11 \
  g++-11 && \
  apt-get -y autoremove --purge && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# install updated cmake
RUN curl -fsSL https://apt.kitware.com/kitware-archive.sh | bash
RUN apt install -y --no-install-recommends cmake ninja-build

ARG DSI_SHA=b7b1f10d6c9599983352050a923a10da4888a30c
ARG TIPL_SHA=3e2a371f47a994d162055675617d7488895eca2a
ARG ATLAS_SHA=e4c2549c42f1858913de7269eac827cc64ae3d29
ARG UNET_SHA=68621730186b9ac18d4610324aecfb7b9196a9fb

RUN mkdir /opt/dsi-studio \
  && cd /opt/dsi-studio \
  && curl -sSLO https://github.com/frankyeh/DSI-Studio/archive/${DSI_SHA}.zip \
  && unzip ${DSI_SHA}.zip \
  && mv DSI-Studio-${DSI_SHA} src \
  && rm -rf ${DSI_SHA}.zip \
  && curl -sSLO https://github.com/frankyeh/TIPL/archive/${TIPL_SHA}.zip \
  && unzip ${TIPL_SHA}.zip \
  && mv TIPL-${TIPL_SHA} src/TIPL \
  && rm ${TIPL_SHA}.zip

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
RUN cd /opt/dsi-studio/src \
  && cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DTIPL_DIR=. \
  && cmake --build ./build --parallel --config Release

RUN cd /opt/dsi-studio \
  && mv src/build/dsi_studio . \
  && chmod 755 dsi_studio \
  && cp -R src/other/* . \
  && rm -rf src \
  && curl -sSLO https://github.com/frankyeh/UNet-Studio-Data/archive/${UNET_SHA}.zip \
  && unzip ${UNET_SHA}.zip \
  && rm ${UNET_SHA}.zip \
  && mv UNet-Studio-Data-${UNET_SHA}/network/ . \
  && rm -rf mv UNet-Studio-Data-${UNET_SHA} \
  && curl -sSLO https://github.com/frankyeh/DSI-Studio-atlas/archive/${ATLAS_SHA}.zip \
  && unzip ${ATLAS_SHA}.zip \
  && rm -rf DSI-Studio-atlas-${ATLAS_SHA}/.git \
  && mv DSI-Studio-atlas-${ATLAS_SHA} atlas \
  && rm ${ATLAS_SHA}.zip
