FROM pennbbl/qsiprep-ants:22.7.1 as base
FROM base as builder
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub

RUN apt update && apt full-upgrade -y && \
  apt install --no-install-recommends -y software-properties-common && \
  add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
  apt-get update && \
  apt install -y --no-install-recommends \
    libboost-all-dev \
    zlib1g-dev \
    wget \
    g++-9 gcc-9 \
    libeigen3-dev

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
    | apt-key add - \
  && apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ bionic main' \
  && apt-get update \
  && apt-get -y install cmake=3.23.2-0kitware1ubuntu18.04.1 cmake-data=3.23.2-0kitware1ubuntu18.04.1

RUN echo 1234
COPY TORTOISEV4 /src/tortoise4

RUN cd /src/tortoise4/TORTOISEV4 && \
    cmake . \
      -DCMAKE_C_COMPILER=/usr/bin/gcc-9 \
      -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 \
      -DUSECUDA=0 \
      -DITK_DIR=/tmp/ants/build/ITKv5-build \
      -DISDEBUG=0 \
      && \
    make

# FROM base
# COPY --from=builder /opt/ants /opt/ants

# LABEL maintainer="ANTsX team: Forked by QSIPrep team" \
#       description="ANTs is part of the ANTsX ecosystem (https://github.com/ANTsX). \
# ANTs Citation: https://pubmed.ncbi.nlm.nih.gov/24879923"

# ENV ANTSPATH="/opt/ants/bin" \
#     PATH="/opt/ants/bin:$PATH" \
#     LD_LIBRARY_PATH="/opt/ants/lib:$LD_LIBRARY_PATH"
# RUN apt-get update \
#     && apt install -y --no-install-recommends zlib1g-dev \
#     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# WORKDIR /data

CMD ["/bin/bash"]
