FROM ubuntu:jammy-20240125
ARG TAG_ANTS

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl git g++ python3 python-is-python3 \
    libeigen3-dev zlib1g-dev libqt5opengl5-dev \
    ca-certificates \
    libqt5svg5-dev libgl1-mesa-dev libfftw3-dev libtiff5-dev libpng-dev unzip

# https://github.com/3Tissue/MRtrix3Tissue/issues/27
ARG MRTRIX_SHA=5f4c31bc93008520c61d59b94af0db3f17b4ab76

ENV PATH="/opt/mrtrix3-latest/bin:$PATH"
RUN cd /opt \
    && curl -sSLO https://github.com/PennLINC/MRtrix3Tissue/archive/${MRTRIX_SHA}.zip \
    && unzip ${MRTRIX_SHA}.zip \
    && mv MRtrix3Tissue-${MRTRIX_SHA} /opt/3Tissue \
    && rm ${MRTRIX_SHA}.zip \
    && cd /opt/3Tissue \
    && ./configure -nogui \
    && echo "Compiling MRtrix3-3Tissue ..." \
    && ./build
