FROM nvidia/cuda:10.2-runtime-ubuntu18.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl git g++ python libeigen3-dev zlib1g-dev libqt5opengl5-dev libqt5svg5-dev libgl1-mesa-dev libfftw3-dev libtiff5-dev libpng-dev unzip

ARG MRTRIX_SHA=c1367255f51a3cbe774c8317448cdc0b0aa587be
ENV PATH="/opt/mrtrix3-latest/bin:$PATH"
RUN cd /opt \
    && curl -sSLO https://github.com/3Tissue/MRtrix3Tissue/archive/${MRTRIX_SHA}.zip \
    && unzip ${MRTRIX_SHA}.zip \
    && mv MRtrix3Tissue-${MRTRIX_SHA} /opt/3Tissue \
    && rm ${MRTRIX_SHA}.zip \
    && cd /opt/3Tissue \
    && ./configure -nogui \
    && echo "Compiling MRtrix3-3Tissue ..." \
    && ./build
