FROM ubuntu:jammy-20240125
ARG TAG_ANTS

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    ca-certificates \
                    curl \
                    libblas-dev \
                    liblapack-dev \
                    build-essential \
                    libgomp1

# Create a shared $HOME directory
RUN useradd -m -s /bin/bash -G users qsiprep
WORKDIR /home/qsiprep
ENV HOME="/home/qsiprep" \
    PIP_DEFAULT_TIMEOUT=100


# Installing and setting up miniconda
RUN curl -sSLO https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh && \
    bash Miniconda3-py310_23.11.0-2-Linux-x86_64.sh -b -p /usr/local/miniconda && \
    rm Miniconda3-py310_23.11.0-2-Linux-x86_64.sh

RUN /usr/local/miniconda/bin/conda install -y \
        numpy=1.26 \
        scipy=1.11 \
        pip \
        pandas=2.2 \
    && /usr/local/miniconda/bin/conda install -y \
        -c conda-forge \
        nodejs=20 \
        graphviz=9.0 \
        fury \
        pandoc=3.1

RUN \
    /usr/local/miniconda/bin/pip install dmri-amico==1.5.4 \
    && /usr/local/miniconda/bin/pip install torch==1.13.1 \
    && /usr/local/miniconda/bin/pip install surfa
RUN /usr/local/miniconda/bin/pip install tensorflow-gpu==2.8.4 keras==2.8.0 protobuf



RUN mkdir -p ${HOME}/.dipy \
    && /usr/local/miniconda/bin/python -c "import amico; amico.core.setup()"
