ARG TAG_ANTS

FROM pennbbl/qsiprep-ants:${TAG_ANTS} as base
FROM base as builder
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub

RUN apt update && apt full-upgrade -y && \
  apt install --no-install-recommends -y software-properties-common && \
  add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
  apt-get update && \
  apt install -y --no-install-recommends \
    zlib1g-dev \
    wget \
    git \
    g++-9 gcc-9 \
    libeigen3-dev fftw3 libfftw3-dev

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
    | apt-key add - \
  && apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ bionic main' \
  && apt-get update \
  && apt-get -y install cmake=3.23.2-0kitware1ubuntu18.04.1 cmake-data=3.23.2-0kitware1ubuntu18.04.1


RUN \
  mkdir /src \
  && cd /src \
  && wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz \
  && tar -xvf boost_1_76_0.tar.gz \
  && cd boost_1_76_0 \
  && ln -s /usr/bin/g++-9 /usr/bin/g++ \
  && ./bootstrap.sh --with-libraries=iostreams,filesystem,system,regex --prefix=/usr/local/boost176 \
  && ./b2 install


ARG TORTOISE_SHA=9fb5296649ef6de802fde25cca4cb2893a94c64d
RUN \
  cd /src \
  && git clone https://github.com/eurotomania/TORTOISEV4.git \
  && cd TORTOISEV4/TORTOISEV4 \
  && cmake . \
      -DCMAKE_C_COMPILER=/usr/bin/gcc-9 \
      -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 \
      -DUSECUDA=0 \
      -DQSIPREP=1 \
      -DITK_DIR=/tmp/ants/build/ITKv5-build \
      -DISDEBUG=0 \
      && \
    make

CMD ["/bin/bash"]
