FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04 as base
ARG TAG_ANTS
FROM base as builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    software-properties-common \
                    build-essential \
                    apt-transport-https \
                    ca-certificates \
                    gnupg \
                    wget \
                    ninja-build \
                    git \
                    zlib1g-dev \
                    bc \
                    cmake \
                    cmake-data && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ARG ANTS_SHA=caa60eb4ad53d561f9ddd72b71a6baf2acac0078
RUN mkdir /tmp/ants \
    && cd /tmp \
    && git clone https://github.com/ANTsX/ANTs.git \
    && mv ANTs /tmp/ants/source \
    && cd /tmp/ants/source \
    && git checkout ${ANTS_SHA} \
    && find /tmp/ants/source -name "*.cmake" -type f -exec sed -i 's/cmake_minimum_required(VERSION [0-9]\.[0-4])/cmake_minimum_required(VERSION 3.5)/g' {} \; \
    && find /tmp/ants/source -name "CMakeLists.txt" -type f -exec sed -i 's/cmake_minimum_required(VERSION [0-9]\.[0-4])/cmake_minimum_required(VERSION 3.5)/g' {} \; \
    && mkdir -p /tmp/ants/build \
    && cd /tmp/ants/build \
    && mkdir -p /opt/ants \
    && git config --global url."https://".insteadOf git:// \
    && cmake \
        -GNinja \
        -DBUILD_TESTING=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DSuperBuild_ANTS_C_OPTIMIZATION_FLAGS="-mtune=x86-64 -march=x86-64" \
        -DSuperBuild_ANTS_CXX_OPTIMIZATION_FLAGS="-mtune=x86-64 -march=x86-64" \
        -DCMAKE_INSTALL_PREFIX=/opt/ants \
        /tmp/ants/source \
    && cmake --build . --parallel 1 \
    && cd ANTS-build \
    && cmake --install . \
    && cd /opt/ants/bin \
    && rm \
        ANTSUseLandmarkImagesToGetAffineTransform \
        ANTSUseLandmarkImagesToGetBSplineDisplacementField \
        ClusterImageStatistics \
        ConvertInputImagePixelTypeToFloat \
        ConvertScalarImageToRGB \
        ConvertToJpg \
        CreateDTICohort \
        DeNrrd \
        ExtractSliceFromImage \
        FitBSplineToPoints \
        KellyKapowski \
        KellySlater \
        NonLocalSuperResolution \
        SuperResolution \
        SurfaceBasedSmoothing \
        TimeSCCAN \
        WarpImageMultiTransform \
        WarpTensorImageMultiTransform \
        WarpTimeSeriesImageMultiTransform \
        antsASLProcessing.sh \
        antsBOLDNetworkAnalysis.R \
        antsCorticalThickness.sh \
        antsIntermodalityIntrasubject.sh \
        antsLandmarkBasedTransformInitializer \
        antsLongitudinalCorticalThickness.sh \
        antsMotionCorr \
        antsMotionCorrDiffusionDirection \
        antsMotionCorrStats \
        antsNetworkAnalysis.R \
        antsNeuroimagingBattery \
        antsSliceRegularizedRegistration \
        antsUtilitiesTesting \
        sccan \
        simpleSynRegistration

FROM base
COPY --from=builder /opt/ants /opt/ants
COPY --from=builder /tmp/ants /tmp/ants

LABEL maintainer="ANTsX team: Forked by QSIPrep team" \
      description="ANTs is part of the ANTsX ecosystem (https://github.com/ANTsX). \
ANTs Citation: https://pubmed.ncbi.nlm.nih.gov/24879923"

ENV ANTSPATH="/opt/ants/bin" \
    PATH="/opt/ants/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/ants/lib:$LD_LIBRARY_PATH"
RUN apt-get update \
    && apt install -y --no-install-recommends zlib1g-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/*

WORKDIR /data

CMD ["/bin/bash"]
