FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04
ARG TAG_ANTS
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub

RUN apt update && apt full-upgrade -y && \
  apt install --no-install-recommends -y software-properties-common && \
  add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
  apt install -y --no-install-recommends \
  unzip \
  curl \
  wget \
  make \
  git \
  libboost-all-dev \
  zlib1g-dev \
  ca-certificates \
  qt6-base-dev \
  libqt6charts6-dev \
  mesa-common-dev \
  libglu1-mesa-dev \
  build-essential \
  ca-certificates \
  gnupg \
  bc \
  ninja-build \
  apt-transport-https \
  gcc-9 \
  g++-9 && \
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9 && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

  RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
    | apt-key add - \
  && apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ jammy main' \
  && apt-get update \
  && apt-get -y install cmake=3.30.2-0kitware1ubuntu22.04.1 \
    cmake-data=3.30.2-0kitware1ubuntu22.04.1
#Need to use a different shell so the QT ENV script works
SHELL ["/bin/bash", "-c"]

ARG DSI_DATE=2025.04.16

ARG TIPL_SHA=1f89c676df1e3577fe524833d2e67063eebb24f3

RUN cd /opt/ \
  && curl -sSLO https://github.com/frankyeh/DSI-Studio/releases/download/${DSI_DATE}/dsi_studio_ubuntu2204_cpu.zip \
  && unzip dsi_studio_ubuntu2204_cpu.zip \
  && rm -rf dsi_studio_ubuntu2204_cpu.zip \
  && curl -sSLO https://github.com/frankyeh/TIPL/archive/${TIPL_SHA}.zip \
  && unzip ${TIPL_SHA}.zip \
  && mv TIPL-${TIPL_SHA} dsi-studio-cpu/TIPL \
  && rm ${TIPL_SHA}.zip \
  && chmod 755 dsi-studio-cpu/dsi_studio

ENV PATH="$PATH:/opt/dsi-studio-cpu"

