ARG TAG_ANTS
FROM pennbbl/qsiprep-ants:${TAG_ANTS} as ants_build
FROM nvidia/cuda:11.7.1-devel-ubuntu22.04 as base

FROM base as builder
COPY --from=ants_build /tmp/ants/build/ITKv5-build /tmp/ants/build/ITKv5-build

RUN apt-get update && \
    apt install -y --no-install-recommends \
      zlib1g-dev \
      wget \
      ca-certificates \
      git \
      g++-11 gcc-11 \
      libeigen3-dev fftw3 libfftw3-dev \
      cmake \
      make

# Without running this, bootstrap.sh can't find the compiler
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
RUN \
  mkdir /src \
  && cd /src \
  && wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz \
  && tar -xvf boost_1_77_0.tar.gz \
  && cd boost_1_77_0 \
  && ./bootstrap.sh --with-libraries=iostreams,filesystem,system,regex --prefix=/usr/local/boost176 \
  && ./b2 install


COPY --from=ants_build /tmp/ants/build/ITKv5 /tmp/ants/build/ITKv5
ARG TORTOISE_SHA=5490b642f54f086f399d2771330e883f09f92834
RUN \
  cd /src \
  && git clone https://github.com/eurotomania/TORTOISEV4.git \
  && cd TORTOISEV4/TORTOISEV4 \
  && git checkout ${TORTOISE_SHA} \
  && cmake . \
      -DCMAKE_C_COMPILER=/usr/bin/gcc-11 \
      -DCMAKE_CXX_COMPILER=/usr/bin/g++-11 \
      -DUSECUDA=1 \
      -DITK_DIR=/tmp/ants/build/ITKv5-build \
      -DISDEBUG=0 \
      && \
    make

CMD ["/bin/bash"]
