FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04
ARG TAG_ANTS
RUN apt-get update && apt-get full-upgrade -y && \
  apt-get install --no-install-recommends -y \
  software-properties-common \
  unzip \
  curl \
  wget \
  make \
  git \
  libboost-all-dev \
  zlib1g-dev \
  ca-certificates \
  qtbase5-dev \
  qtbase5-dev-tools \
  qt5-qmake \
  qtchooser \
  libqt5charts5-dev \
  libqt5opengl5-dev \
  mesa-common-dev \
  libglu1-mesa-dev \
  build-essential \
  gnupg \
  bc \
  ninja-build \
  apt-transport-https && \
  wget -O /tmp/kitware-archive.key https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null && \
  gpg --dearmor /tmp/kitware-archive.key && \
  mv /tmp/kitware-archive.key.gpg /usr/share/keyrings/kitware-archive-keyring.gpg && \
  echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main" > /etc/apt/sources.list.d/kitware.list && \
  apt-get update && \
  apt-get -y install cmake cmake-data && \
  update-alternatives --install /usr/bin/qmake qmake /usr/lib/qt5/bin/qmake 100 && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# This version of DSI Studio is the one used in Chen, which
# we found was more accurate for infant autotrack.
# It was the bundled version of DSI Studio in qsiprep 0.20.0,
# which built off of pennbbl/qsiprep_build:24.1.4.
# In that build TAG_DSISTUDIO was set to 23.7.1

ARG DSI_SHA=8118e168f096c897dcc40f9ecc3ba72b1925cb7d
ARG TIPL_SHA=485a9b140ee4544a1e9c9c084b9d1012ff0b1523

RUN mkdir /opt/dsi-studio \
  && cd /opt/dsi-studio \
  && curl -sSLO https://github.com/frankyeh/DSI-Studio/archive/${DSI_SHA}.zip \
  && unzip ${DSI_SHA}.zip \
  && mv DSI-Studio-${DSI_SHA} src \
  && rm -rf ${DSI_SHA}.zip \
  && curl -sSLO https://github.com/frankyeh/TIPL/archive/${TIPL_SHA}.zip \
  && unzip ${TIPL_SHA}.zip \
  && mv TIPL-${TIPL_SHA} src/TIPL \
  && rm ${TIPL_SHA}.zip \
  && mkdir build && cd build \
  && qmake ../src && make -j 1

ARG ATLAS_SHA=e2e00a8a09cf735c1e6018c258f239586bd77d68

RUN mkdir -p /opt/dsi-studio/dsi_studio_64 \
  && cd /opt/dsi-studio/dsi_studio_64 \
  && curl -sSLO https://github.com/frankyeh/DSI-Studio-atlas/archive/${ATLAS_SHA}.zip \
  && unzip ${ATLAS_SHA}.zip \
  && mv atlas-${ATLAS_SHA} atlas \
  && rm ${ATLAS_SHA}.zip \
  && mv ../build/dsi_studio . \
  && rm -rf /opt/dsi-studio/src /opt/dsi-studio/build