FROM nvidia/cuda:10.2-runtime-ubuntu18.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    ca-certificates \
                    curl

# Installing freesurfer
RUN curl -sSL https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.1/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz \
    | tar zxv --no-same-owner -C /opt \
    --exclude='freesurfer/diffusion' \
    --exclude='freesurfer/docs' \
    --exclude='freesurfer/fsfast' \
    --exclude='freesurfer/lib/*' \
    --exclude='freesurfer/matlab' \
    --exclude='freesurfer/mni/*' \
    --exclude='freesurfer/average/*' \
    --exclude='freesurfer/subjects/*' \
    --exclude='freesurfer/trctrain'

RUN find /opt/freesurfer/bin -type f -not \( \
        -name mri_rigid_register -or \
        -name mri_robust_register -or \
        -name mri_robust_register.bin -or \
        -name mri_robust_template -or \
        -name lta_convert -or \
        -name lta_diff \) \
        -delete \
    && cd /opt/freesurfer
         

