ARG TAG_ANTS

FROM pennbbl/qsiprep-ants:${TAG_ANTS} as base
FROM base as builder

RUN apt-get update && \
    apt install -y --no-install-recommends \
      zlib1g-dev \
      wget \
      ca-certificates \
      git \
      g++-11 gcc-11 \
      libeigen3-dev fftw3 libfftw3-dev \
      cmake \
      make

# Without running this, bootstrap.sh can't find the compiler
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
RUN \
  mkdir /src \
  && cd /src \
  && wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz \
  && tar -xvf boost_1_77_0.tar.gz \
  && cd boost_1_77_0 \
  && ./bootstrap.sh --with-libraries=iostreams,filesystem,system,regex --prefix=/usr/local/boost176 \
  && ./b2 install


ARG TORTOISE_SHA=9fb5296649ef6de802fde25cca4cb2893a94c64d
RUN \
  cd /src \
  && git clone https://github.com/eurotomania/TORTOISEV4.git \
  && cd TORTOISEV4/TORTOISEV4 \
  && git checkout ${TORTOISE_SHA} \
  && cmake . \
      -DCMAKE_C_COMPILER=/usr/bin/gcc-11 \
      -DCMAKE_CXX_COMPILER=/usr/bin/g++-11 \
      -DUSECUDA=0 \
      -DQSIPREP=1 \
      -DITK_DIR=/tmp/ants/build/ITKv5-build \
      -DISDEBUG=0 \
      && \
    make

CMD ["/bin/bash"]
