FROM ubuntu:jammy-20240125
ARG TAG_ANTS

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl git g++ python3 python-is-python3 \
    ca-certificates libeigen3-dev zlib1g-dev libqt5opengl5-dev libqt5svg5-dev libgl1-mesa-dev libfftw3-dev libtiff5-dev libpng-dev unzip

ARG MRTRIX_SHA=670e7b0625572f8b1f13b2793bde506526985d55
ENV PATH="/opt/mrtrix3-latest/bin:$PATH"
RUN cd /opt \
    && curl -sSLO https://github.com/MRtrix3/mrtrix3/archive/${MRTRIX_SHA}.zip \
    && unzip ${MRTRIX_SHA}.zip \
    && mv mrtrix3-${MRTRIX_SHA} /opt/mrtrix3-latest \
    && rm ${MRTRIX_SHA}.zip \
    && cd /opt/mrtrix3-latest \
    && ./configure -nogui \
    && echo "Compiling MRtrix3 ..." \
    && ./build


