#!/bin/bash

# Versions of the component images
export TAG_FREESURFER=26.9.2
export TAG_MRTRIX3=26.1.0
export TAG_MRTRIX3DEV=26.9.1
export TAG_3TISSUE=26.1.0
export TAG_DSISTUDIO=26.1.2
export TAG_DSISTUDIOCHEN=26.7.1
export TAG_AFNI=AFNI_25.2.09
export TAG_TORTOISE=26.9.3
export TAG_TORTOISECUDA=26.9.3
export TAG_SYNB0=26.1.2
export TAG_NIIMATH=26.9.4

echo "Settings:"
echo "----------"
echo ""
echo "TAG_FREESURFER=${TAG_FREESURFER}"
echo "TAG_MRTRIX3=${TAG_MRTRIX3}"
echo "TAG_MRTRIX3DEV=${TAG_MRTRIX3DEV}"
echo "TAG_3TISSUE=${TAG_3TISSUE}"
echo "TAG_DSISTUDIO=${TAG_DSISTUDIO}"
echo "TAG_DSISTUDIOCHEN=${TAG_DSISTUDIOCHEN}"
echo "TAG_AFNI=${TAG_AFNI}"
echo "TAG_TORTOISE=${TAG_TORTOISE}"
echo "TAG_TORTOISECUDA=${TAG_TORTOISECUDA}"
echo "TAG_SYNB0=${TAG_SYNB0}"
echo "TAG_NIIMATH=${TAG_NIIMATH}"
